### ISSUE TITLE
Autocomplete field not working for me

### ISSUE THREAD

**Issue by sbgraphicdesign** [backdrop-contrib/entityreference#16]
Have set the Entity reference field to Autocomplete, but when I type into the field it does not return the results as it should. I always just have the same first 10 nodes as per the sorting set on the field.

Have tried both changing the field setting to "contains" and "start with" and I get the same behaviour.

The field is currently set to "Unlimited" results in Simple mode. I have several hundred nodes to refer from so a select list is out of the question.

Not seeing any errors in the browser console or error log.

Also I do have more than one Entity Reference field on the node (3 in total) and only the one that is set to a select list works.

**Comment by herbdool** [comment]
Do you see the same issue if you set it use a View?

**Comment by sbgraphicdesign** [comment]
I didn't use a view, and unfortunately I've now abandoned Entity Reference for the References Module (which works fine).

However, in the interests of helping out, I'll test it for you using a View as I'm working on the site right now. Will report back presently

**Comment by sbgraphicdesign** [comment]
> Do you see the same issue if you set it use a View?

No I do not. Having now tested, using a view for the list, indeed, works as it should.

**Comment by herbdool** [comment]
I'm unable to recreate this. I've recently squashed some bugs so this might be working now when using the Simple select (not a View). Please reopen if it still occurs.
