### ISSUE TITLE
Enabling Entity Reference dependency requires Entity Plus which causes Internal Server Error With Rules requirement

### ISSUE THREAD

**Issue by kelizoliva** [backdrop-contrib/entityreference#17]
Trying to use this with Backdrop 1.12.3, but running into an Internal Server Error when attempting to enable its dependency, Entity Plus.

`[Tue Feb 26 17:06:26.496251 2019] [:error] [pid 28599] [client 66.215.32.108:56043] PHP Fatal error:  Cannot redeclare entity_metadata_wrapper() (previously declared in /var/www/test/[client]/public/modules/entity_metadata_wrapper/entity_metadata_wrapper.module:10) in /var/www/test/[client]/public/modules/entity_plus/entity_plus.module on line 28, referer: https://[client].palantetech.coop/admin/modules/list/confirm`

So I disabled entity_metadata_wrapper, as well as modules dependent upon it (rules and rules ui), and attempted to enable both entity_plus and entityreference again which was fine, but now I am unable to re-enable rules and rules ui without enabling entity_metadata_wrapper. 

So does this mean that this module is not viable, given that it conflicts with Rules, which is a pretty major module?

**Comment by laryn** [comment]
There is an issue in progress to convert Rules to be dependent on Entity Plus as well, as that is the long term solution:

 - https://github.com/backdrop-contrib/rules/issues/27

I have a branch in development to try to make this happen. Not sure if you are interested/able in helping test and debug, but it is here:

 - https://github.com/laryn/rules/tree/EntityPlus

**Comment by kelizoliva** [comment]
Ah, good to know, thank you!

Alas I am too slammed with work at the moment to be able to do much contributing right now, but i will keep an eye on this!

**Comment by kelizoliva** [comment]
Switched to EntityPlus now that Rules has switched, this runs fine so far.
