### ISSUE TITLE
Field cannot be null even if it is not set to required

### ISSUE THREAD

**Issue by kelizoliva** [backdrop-contrib/entityreference#19]
I have an entity reference field for node reference set up on a node type. It is a select list, with default value set to -None-. When I create a new node, but do not select the entity reference, I receive the following error:

`PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'field_technical_assistance_refer_target_id' cannot be null: INSERT INTO {field_data_field_technical_assistance_refer} (entity_type, entity_id, revision_id, bundle, delta, language, field_technical_assistance_refer_target_id) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6); Array ( [:db_insert_placeholder_0] => node [:db_insert_placeholder_1] => 74 [:db_insert_placeholder_2] => 91 [:db_insert_placeholder_3] => organization [:db_insert_placeholder_4] => 0 [:db_insert_placeholder_5] => und [:db_insert_placeholder_6] => ) in field_sql_storage_field_storage_write() (line 444 of /var/www/[PATH]/core/modules/field/modules/field_sql_storage/field_sql_storage.module).`

and

`EntityStorageException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'field_technical_assistance_refer_target_id' cannot be null in NodeStorageController->save() (line 320 of /var/www/test/sec/public/core/modules/node/node.entity.inc).`

Is there some reason that if an entity reference field exists, it cannot be null?

**Comment by herbdool** [comment]
I've recently squashed some bugs, and just tried to recreate this. I wasn't able to, so perhaps this is working now? Please reopen if it's still occurring for you.

**Comment by olafgrabienski** [comment]
@herbdool On one of my sites, I've just updated Entity Reference to 1.x-1.6.0, and the error still exists for me. In contrast to @kelizoliva, I'm using a autocomplete field. When I try to create a post without a value for the Entity Reference field, I get a white page with "SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'field_MYFIELD_target_id' cannot be null ". In DBlog, I find messages like the ones mentioned in the issue description.

Note that the issue happens only when *creating* content. So, it is possible to save new content first *with* a value in the ER field, then edit it, remove the value, and save again.

**Comment by herbdool** [comment]
@olafgrabienski I think there might be something else going on. I tried to recreate the bug by setting up a demo site with Tugboat and then installing entity reference and creating a field. It saves the node fine without throwing an sql error. Can you try it on a fresh site?

**Comment by olafgrabienski** [comment]
@herbdool You're right, there must be something else. I've tried to reproduce the issue on a demo site, but there it works like a charm. On the demo site I've also simulated some of the configuration of my problematic site (Localization, Field group a View to select the Reference), but still no issue. The problematic site has been upgraded from Drupal 7, but I've no specific ideas regarding this. Do you have an idea from the error text what else to look for?

**Comment by herbdool** [comment]
I'm not sure. Are there other errors showing up in the logs to give additional clues? You could also enable devel and put `ddebug_backtrace()` into the line in `field_sql_storage.module` which is reporting the error. Might give a clue as to some other module.

So it's correct that the column can't be NULL in the db, but it should not be trying to write a row if there was no target_id selected.
