### ISSUE TITLE
Seems to mostly work

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/entityreference#2]
Your fork does seem to work well enough. I had to make a couple initial fixes:

* remove _element_validate_integer_positive and use the html5 number element
* in hook_autoload_info change the slashes in the path from \ to /

Like you mention in a backdrop-contrib thread, entity_access could just return TRUE until this function (and also access callbacks for entities?) is put into core. I imagine this would be a problem for the reference module as well.

I'm circling back to your fork since the new Reference module seems to be stalled and I wanted to know how usable this is.

**Comment by herbdool** [comment]
PR #3

**Comment by docwilmot** [comment]
I'd forgotten I started this @herbdool so transferring over to backdrop-contrib. Feel free to consider yourself a maintainer and push changes directly.
Thanks

**Comment by docwilmot** [comment]
@herbdool also, re the `entity_access()` function, I think we could rename that function to `entityreference_entity_access()` and let it explicitly check for access rights with code like:
```
if (function_exists($entity->entityId() . '_access')) {
  $function = $entity->entityId() . '_access';
  return $function($op, etc);
```
This would at least do proper access checking for core entities.

**Comment by herbdool** [comment]
I was thinking in that ballpark as well but the tricky thing is that not every function with that pattern behaves the same way. For instance, `user_access()` is expecting a permission string and `taxonomy_term_access` only works with edit or delete.

So we might be better off having a switch statement and defaulting to returning TRUE.

**Comment by docwilmot** [comment]
> So we might be better off having a switch statement and defaulting to returning TRUE.

Yep
