### ISSUE TITLE
Remove dependency on entity_plus

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/entityreference#21]
This can be done but may require core adding support for entity_view() and a view method on the entity controller.

**Comment by docwilmot** [comment]
Not really though, we'd just need to copy and modify the code from `EntityPlusController::view()` to a function and rename it `entityreference_view()` or something similar.

**Comment by herbdool** [comment]
Yeah, that is an alternative that I thought of too. But I was thinking that since there's an issue to add support for this in core, that would be the better route. The only caveat is how entity_plus had provided support for hiding the titles of entities. Not sure if that will be supported in core. Currently none of the ENTITY_view functions in core support that. So perhaps it will still need a custom solution here to maintain backwards-compatibility.

And the other goal is to ensure the module is a candidate for core (if we get consensus on that).

**Comment by herbdool** [comment]
A link to the function https://github.com/backdrop-contrib/entity_plus/blob/4acf2f69ee87704fc836df04d73ba811d15160a5/includes/entity_plus.controller.inc#L706.

I suppose if core provides a hook in the view method that might work too.

The core issue: https://github.com/backdrop/backdrop-issues/issues/1739

**Comment by herbdool** [comment]
@docwilmot I've got a PR for this now. Couldn't stop thinking about. I figured it would best to theme it within the module so that we can determine if page title or links should be displayed. So, yes, I copied and adapted a bunch of stuff from Entity Plus to build the content. Hoping for someone to kick the tires before I merge.

**Comment by docwilmot** [comment]
One way to kick the tires is comprehensive tests. From your knowledge of the code, would you say tests cover everything?

**Comment by herbdool** [comment]
The tests are fairly good. I had to work on it a bit more to ensure the current settings work properly. https://github.com/backdrop-contrib/entityreference/pull/24.

I should probably add a test for files. I think there's a core bug with file display, or assumption but I've got a workaround.

At any rate don't need entity_plus.

**Comment by herbdool** [comment]
Compared with Drupal 7's entityreference module. There are too many particulars with each entity type's template. I tried at first to add some of those exceptions for nodes, files, comments but what's even better is to just use the new entity methods in core: `buildContent()` and `view()`.
