### ISSUE TITLE
Add submodules for behavior example, helpers for feeds, migrate, devel_generate, diff, etc.

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/entityreference#25]
In D7 there were a few files, such as an example plugin, integration for feeds, migrate, devel_generate, diff. Could wrap them all up in a submodule, whatever makes the most sense in case a reference module makes it into core.

**Comment by laryn** [comment]
There has been a bit of interest in kickstarting the Organic Groups port recently, so I just installed it in its current state on a vanilla install to refresh my memory on how far along it is, and I ran into this pretty early on:

> Fatal error: Class 'EntityReference_BehaviorHandler_Abstract' not found in /app/modules/og-1.x-2.x/plugins/entityreference/behavior/OgBehaviorHandler.class.php on line 6

**Comment by herbdool** [comment]
You'll need to move your issue to OG. The abstract class has been renamed. I can't recall exactly but if you take a peak you'll see.

**Comment by laryn** [comment]
Thanks @herbdool

**Comment by herbdool** [comment]
I realized this issue is originally about something else. Reopening

**Comment by laryn** [comment]
Sorry @herbdool

**Comment by herbdool** [comment]
Closing because each of these can end up in their respective modules: feeds, devel, migrate, diff.
