### ISSUE TITLE
Old ctools functionality and code leftover

### ISSUE THREAD

**Issue by rbargerhuff** [backdrop-contrib/entityreference#27]
Hello,

My colleague ran into an issue where when migrating from Drupal 7 due to old `ctools` functionality being leftover after the  conversion to Backdrop CMS. This old functionality must be removed in order for a Drupal 7 migration to be successful.

**Comment by herbdool** [comment]
The behaviour plugins were renamed at some point from `views-select-list` to `views` and from `taxonomy-index` to `taxonomy`. From what I can tell that happened during the initial port: https://github.com/backdrop-contrib/entityreference/commit/bb4938eb8277b1abb5fe9de0c8e04f966eb8b4a3. I agree with the direction of the PR but I may tweak it before merging.
