### ISSUE TITLE
Notice: Undefined index: #theme in entityreference_field_formatter_view() (line 1381 of

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entityreference#34]
A recent addition  to `entityreference.module` (line 1381) is generating this notice with custom entities that use Entity Plus.

This is a bit tricky to reproduce - you'd need to create a custom entity that uses `EntityPlusController::view()` to return the view array. 

At the core of the issue is that `entity_plus_view()` and `EntityPlusController::view()` (unlike `entity_view()` and `Entity::view()`)  return the renderable array deep WITHIN an array. Compare the array structures returned by `entity_plus_view()` and `entity_view()` below.

This is a rare case, but I have just now encountered it a couple of times while working with custom entities. The problem with `entityreference.module` line 1381 is that it assume that the key `['#theme']` exists. This key DOES exist within the renderable array - but the problem is that the actual renderable array is buried under 2 levels in the case of `EntityPlusController::view()` and `entity_plus_view()`. This will also be the case with ALL entity classes that use the controller `EntityPlusController` and others derived from D7's Entity API's `EntityAPIController`.

Proposed solution:  a quick solution is to check that `['#theme']` before line 1381. If not, then set it. However, this may mean that the '#theme' key is added on the wrong level of the array and will be ignored. So, perhaps a bit more code is needed to get to the correct level of the array structure. The alternative (changing EntityPlusController) is just TOO risky and will affect many contrib modules.

-----
For these snapshots I created a custom entity called Piece that uses `EntityPlusController::view()`

Output of `entity_view($piece)`
<img width="1089" alt="Screen Shot 2022-07-01 at 10 18 38 AM" src="https://user-images.githubusercontent.com/9938978/176932623-a67a035f-ef5c-450c-93c9-87977cc2ef3d.png">

Output of `entity_plus_view('piece', array($piece));`   
<img width="1088" alt="Screen Shot 2022-07-01 at 10 18 29 AM" src="https://user-images.githubusercontent.com/9938978/176932646-1ee703fa-450c-476d-b2b6-8599b8c1c7d1.png">

**Comment by argiepiano** [comment]
PR #34.

I added a recursive helper that adds '__entityreference' to the `#theme` key. I've tested with custom AND core entities, and it's working for me.

**Comment by argiepiano** [comment]
OK, actually there is an easier way (in my case) to avoid this problem without the PR.

My entity `view` method was modeled after D7 Entity API's `Entity:view()` which looks like this:

```php
  public function view($view_mode = 'full', $langcode = NULL, $page = NULL) {
    return entity_get_controller($this->entityType)->view(array($this), $view_mode, $langcode, $page);
  }
```
Instead I should have modeled my view method based on BACKDROP's `Entity::view()`, which looks like this:

```php
  public function view($view_mode = 'full', $langcode = NULL, $page = NULL) {
    $view = entity_get_controller($this->entityType())->view(array($this->id() => $this), $view_mode, $langcode, $page);
    return $view[$this->entityType()][$this->id()];
  }
```

So, I guess this is mostly a non-issue. The key here is for developers to be aware that D7 and Backdrop's `Entity` are different.

**Comment by argiepiano** [comment]
@herbdool  - should I then close this and the PR? Thoughts?

**Comment by herbdool** [comment]
Sure. You can always revive it later.
